### ISSUE TITLE
examples ImportError: No module found & FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml

### ISSUE THREAD

**Issue by zicmama** [pimoroni/inky#33]
```
pi@raspberrypi:~/inky/examples/phat $ ./weather-phat.py -c yellow
Traceback (most recent call last):
  File "./weather-phat.py", line 9, in <module>
    from font_fredoka_one import FredokaOne
ImportError: No module named font_fredoka_one

```
Font error also occurs on name-badge.py
Is there a pip install missing?

**Comment by zicmama** [comment]
sudo pip install font_fredoka_one
sudo pip install font_hanken_grotesk

**Comment by zicmama** [comment]
```
pi@raspberrypi:~/inky/examples/phat $ ./weather-phat.py -c yellow
Inky pHAT: Weather

Displays weather information for a given location. The default location is Sheffield-on-Sea.


Traceback (most recent call last):
  File "./weather-phat.py", line 99, in <module>
    weather = get_weather(location_string)
  File "./weather-phat.py", line 63, in get_weather
    soup = BeautifulSoup(res.content, "lxml")
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 196, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by zicmama** [comment]
sudo pip install lxml

**Comment by zicmama** [comment]
```
Collecting lxml
  Downloading https://files.pythonhosted.org/packages/7d/29/174d70f303016c58bd790c6c86e6e86a9d18239fac314d55a9b7be501943/lxml-4.3.3.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 18kB/s 
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Yirncw/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpULTRyUpip-wheel- --python-tag cp27:
  Building lxml version 4.3.3.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv6l-2.7
  creating build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-armv6l-2.7/lxml
  creating build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-armv6l-2.7/lxml/includes
  creating build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-armv6l-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-armv6l-2.7/lxml/html
  creating build/lib.linux-armv6l-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv6l-2.7/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv6l-2.7/lxml
  copying src/lxml/includes/uri.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv6l-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv6l-2.7/lxml/includes
  creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources
  creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-armv6l-2.7
  creating build/temp.linux-armv6l-2.7/src
  creating build/temp.linux-armv6l-2.7/src/lxml
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv6l-2.7/src/lxml/etree.o -w
  In file included from src/lxml/etree.c:687:0:
  src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
   #include "libxml/xmlversion.h"
                                 ^
  compilation terminated.
  Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitIapb9H.c -o tmp/xmlXPathInitIapb9H.o
  /tmp/xmlXPathInitIapb9H.c:1:26: fatal error: libxml/xpath.h: No such file or directory
   #include "libxml/xpath.h"
                            ^
  compilation terminated.
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml
  Running setup.py install for lxml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Yirncw/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Sn7Z5e-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 4.3.3.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv6l-2.7
    creating build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/sax.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/__init__.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/builder.py -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-armv6l-2.7/lxml
    creating build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-armv6l-2.7/lxml/includes
    creating build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-armv6l-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-armv6l-2.7/lxml/html
    creating build/lib.linux-armv6l-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv6l-2.7/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv6l-2.7/lxml
    copying src/lxml/includes/uri.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv6l-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv6l-2.7/lxml/includes
    creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources
    creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/rng
    creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv6l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-armv6l-2.7
    creating build/temp.linux-armv6l-2.7/src
    creating build/temp.linux-armv6l-2.7/src/lxml
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv6l-2.7/src/lxml/etree.o -w
    In file included from src/lxml/etree.c:687:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitrW1A2t.c -o tmp/xmlXPathInitrW1A2t.o
    /tmp/xmlXPathInitrW1A2t.c:1:26: fatal error: libxml/xpath.h: No such file or directory
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Yirncw/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Sn7Z5e-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Yirncw/lxml/

```

**Comment by Gadgetoid** [comment]
In case where pip packages wont build, you can try ones from apt. In this case either:

```sudo apt install python-lxml```

or

```sudo apt install python3-lxml```

**Comment by zicmama** [comment]
worked for me! Thanks
